spring.application.name=ktp-api

spring.datasource.url=jdbc:mysql://localhost:3306/spring
spring.datasource.username=root
spring.datasource.password=Semogaditerima123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
